# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import (
    apply_arithmetic_operation_over_rows as apply_arithmetic_operation_over_rows,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_mean as dataframe_column_mean,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import dataframe_count as dataframe_count
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import filter_df as filter_df
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_apn.tasks import (
    draw_time_series_bar_chart_grouped as draw_time_series_bar_chart_grouped,
)
from ecoscope_workflows_ext_apn.tasks import (
    extract_array_length_from_json_column as extract_array_length_from_json_column,
)
from ecoscope_workflows_ext_apn.tasks import (
    gather_apn_dashboard as gather_apn_dashboard,
)
from ecoscope_workflows_ext_apn.tasks import join_list_column as join_list_column
from ecoscope_workflows_ext_custom.tasks.transformation import (
    to_quantity as to_quantity,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    locale = (
        task(set_locale)
        .validate()
        .set_task_instance_id("locale")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(locale_str="es_ES", **(params.get("locale") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    patente = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("patente")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patente") or {}))
        .call()
    )

    events = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "priority",
                "event_type",
                "location",
                "event_category",
                "reported_by",
                "serial_number",
                "state",
                "geometry",
                "event_details",
            ],
            event_types=["libro_diario_vehicular_v2"],
            include_details=True,
            raise_on_empty=False,
            include_updates=False,
            include_null_geometry=True,
            include_display_values=True,
            include_related_events=False,
            **(params.get("events") or {}),
        )
        .call()
    )

    processed_events = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("processed_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events,
            client=er_client,
            map_to_titles=False,
            ordered=True,
            **(params.get("processed_events") or {}),
        )
        .call()
    )

    extract_patente = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_patente")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=processed_events,
            column_name="event_details",
            field_name_options=["Patente"],
            output_column_name="patente",
            output_type="str",
            **(params.get("extract_patente") or {}),
        )
        .call()
    )

    vehicle_data = (
        task(filter_df)
        .validate()
        .set_task_instance_id("vehicle_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_patente,
            column_name="patente",
            op="equal",
            value=patente,
            reset_index=False,
            **(params.get("vehicle_data") or {}),
        )
        .call()
    )

    extract_km_salida = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_km_salida")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=vehicle_data,
            column_name="event_details",
            field_name_options=["KM_de_salida"],
            output_column_name="km_salida",
            output_type="float",
            **(params.get("extract_km_salida") or {}),
        )
        .call()
    )

    extract_km_llegada = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_km_llegada")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_km_salida,
            column_name="event_details",
            field_name_options=["Km_de_llegada"],
            output_column_name="km_llegada",
            output_type="float",
            **(params.get("extract_km_llegada") or {}),
        )
        .call()
    )

    extract_litros = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_litros")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_km_llegada,
            column_name="event_details",
            field_name_options=["Litros_cargados"],
            output_column_name="litros_cargados",
            output_type="float",
            **(params.get("extract_litros") or {}),
        )
        .call()
    )

    extract_tipo_combustible = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_tipo_combustible")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_litros,
            column_name="event_details",
            field_name_options=["Tipo_de_combustible"],
            output_column_name="tipo_combustible",
            output_type="str",
            **(params.get("extract_tipo_combustible") or {}),
        )
        .call()
    )

    extract_ocupantes = (
        task(extract_array_length_from_json_column)
        .validate()
        .set_task_instance_id("extract_ocupantes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_tipo_combustible,
            column_name="event_details",
            field_name="Pasajeros",
            output_column_name="ocupantes",
            **(params.get("extract_ocupantes") or {}),
        )
        .call()
    )

    extract_objetivo = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_objetivo")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_ocupantes,
            column_name="event_details",
            field_name_options=["Motivo_del_desplazamiento"],
            output_column_name="objetivo",
            output_type="str",
            **(params.get("extract_objetivo") or {}),
        )
        .call()
    )

    format_objetivo = (
        task(join_list_column)
        .validate()
        .set_task_instance_id("format_objetivo")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_objetivo,
            column_name="objetivo",
            separator=", ",
            **(params.get("format_objetivo") or {}),
        )
        .call()
    )

    extract_origen = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_origen")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=format_objetivo,
            column_name="event_details",
            field_name_options=["Origen_del_desplazamiento"],
            output_column_name="origen",
            output_type="str",
            **(params.get("extract_origen") or {}),
        )
        .call()
    )

    extract_destino = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_destino")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_origen,
            column_name="event_details",
            field_name_options=["Destino"],
            output_column_name="destino",
            output_type="str",
            **(params.get("extract_destino") or {}),
        )
        .call()
    )

    extract_hora_llegada = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_hora_llegada")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_destino,
            column_name="event_details",
            field_name_options=["Regreso"],
            output_column_name="regreso",
            output_type="str",
            **(params.get("extract_hora_llegada") or {}),
        )
        .call()
    )

    extract_chofer = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_chofer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_hora_llegada,
            column_name="event_details",
            field_name_options=["Chofer"],
            output_column_name="chofer",
            output_type="str",
            **(params.get("extract_chofer") or {}),
        )
        .call()
    )

    extract_forma_recarga = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_forma_recarga")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_chofer,
            column_name="event_details",
            field_name_options=["Forma_de_recarga"],
            output_column_name="forma_recarga",
            output_type="str",
            **(params.get("extract_forma_recarga") or {}),
        )
        .call()
    )

    extract_responsable_recarga = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_responsable_recarga")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_forma_recarga,
            column_name="event_details",
            field_name_options=["Responsable_de_la_recarga"],
            output_column_name="responsable_recarga",
            output_type="str",
            **(params.get("extract_responsable_recarga") or {}),
        )
        .call()
    )

    km_por_viaje = (
        task(apply_arithmetic_operation_over_rows)
        .validate()
        .set_task_instance_id("km_por_viaje")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_responsable_recarga,
            column_a="km_llegada",
            column_b="km_salida",
            output_column="km_viaje",
            operation="subtract",
            **(params.get("km_por_viaje") or {}),
        )
        .call()
    )

    total_journeys = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("total_journeys")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=km_por_viaje, **(params.get("total_journeys") or {}))
        .call()
    )

    total_journeys_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_journeys_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total de desplazamientos",
            decimal_places=0,
            data=total_journeys,
            **(params.get("total_journeys_sv") or {}),
        )
        .call()
    )

    total_km = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_km")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=km_por_viaje, column_name="km_viaje", **(params.get("total_km") or {})
        )
        .call()
    )

    total_km_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_km_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Kilómetros totales recorridos",
            decimal_places=0,
            data=total_km,
            **(params.get("total_km_sv") or {}),
        )
        .call()
    )

    total_fuel = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_fuel")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=km_por_viaje,
            column_name="litros_cargados",
            **(params.get("total_fuel") or {}),
        )
        .call()
    )

    total_fuel_q = (
        task(to_quantity)
        .validate()
        .set_task_instance_id("total_fuel_q")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(value=total_fuel, unit="L", **(params.get("total_fuel_q") or {}))
        .call()
    )

    total_fuel_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_fuel_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total de combustible consumido",
            decimal_places=0,
            data=total_fuel_q,
            **(params.get("total_fuel_sv") or {}),
        )
        .call()
    )

    avg_occupants = (
        task(dataframe_column_mean)
        .validate()
        .set_task_instance_id("avg_occupants")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=km_por_viaje,
            column_name="ocupantes",
            **(params.get("avg_occupants") or {}),
        )
        .call()
    )

    avg_occupants_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("avg_occupants_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Promedio de ocupantes",
            decimal_places=1,
            data=avg_occupants,
            **(params.get("avg_occupants_sv") or {}),
        )
        .call()
    )

    km_over_time_chart = (
        task(draw_time_series_bar_chart_grouped)
        .validate()
        .set_task_instance_id("km_over_time_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=km_por_viaje,
            x_axis="time",
            y_axis="km_viaje",
            category="patente",
            agg_function="sum",
            time_interval="month",
            layout_style={
                "title": "Kilómetros recorridos en el tiempo",
                "title_x": 0.5,
                "font_size": None,
                "font_color": None,
                "font_style": None,
                "plot_bgcolor": None,
                "showlegend": False,
                "hovermode": "x unified",
                "legend_title": None,
                "xaxis": {"title": "Mes", "range": None},
                "yaxis": {"title": "Kilómetros (km)", "range": None},
                "bargap": 0.2,
                "bargroupgap": 0.1,
            },
            **(params.get("km_over_time_chart") or {}),
        )
        .call()
    )

    km_over_time_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("km_over_time_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=km_over_time_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="km_over_time_chart",
            **(params.get("km_over_time_chart_html") or {}),
        )
        .call()
    )

    km_over_time_chart_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("km_over_time_chart_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Kilómetros recorridos en el tiempo",
            data=km_over_time_chart_html,
            **(params.get("km_over_time_chart_sv") or {}),
        )
        .call()
    )

    driver_ranking_data = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("driver_ranking_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=km_por_viaje,
            groupby_cols=["chofer"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Kilómetros recorridos",
                    "aggregator": "sum",
                    "column": "km_viaje",
                    "decimal_places": 0,
                },
                {
                    "display_name": "Cantidad de desplazamientos",
                    "aggregator": "count",
                    "column": "km_viaje",
                    "decimal_places": 0,
                },
            ],
            **(params.get("driver_ranking_data") or {}),
        )
        .call()
    )

    driver_ranking_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("driver_ranking_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=driver_ranking_data,
            raise_if_not_found=False,
            retain_columns=[
                "chofer",
                "Kilómetros recorridos",
                "Cantidad de desplazamientos",
            ],
            rename_columns={"chofer": "Nombre"},
            drop_columns=None,
            **(params.get("driver_ranking_columns") or {}),
        )
        .call()
    )

    driver_ranking_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("driver_ranking_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=driver_ranking_columns,
            **(params.get("driver_ranking_table") or {}),
        )
        .call()
    )

    driver_ranking_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("driver_ranking_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=driver_ranking_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="driver_ranking_table",
            **(params.get("driver_ranking_table_html") or {}),
        )
        .call()
    )

    driver_ranking_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("driver_ranking_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Ranking de choferes",
            data=driver_ranking_table_html,
            **(params.get("driver_ranking_sv") or {}),
        )
        .call()
    )

    vehicle_usage_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("vehicle_usage_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=km_por_viaje,
            raise_if_not_found=False,
            retain_columns=[
                "time",
                "regreso",
                "litros_cargados",
                "tipo_combustible",
                "objetivo",
                "origen",
                "destino",
                "km_viaje",
            ],
            rename_columns={
                "time": "Fecha de inicio",
                "regreso": "Fecha de fin",
                "litros_cargados": "Cantidad de combustible (litros)",
                "tipo_combustible": "Tipo de combustible",
                "objetivo": "Objetivo",
                "origen": "Origen",
                "destino": "Destino",
                "km_viaje": "Distancia recorrida (km)",
            },
            drop_columns=None,
            **(params.get("vehicle_usage_columns") or {}),
        )
        .call()
    )

    vehicle_usage_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("vehicle_usage_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=vehicle_usage_columns, **(params.get("vehicle_usage_table") or {})
        )
        .call()
    )

    vehicle_usage_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("vehicle_usage_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=vehicle_usage_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="vehicle_usage_table",
            **(params.get("vehicle_usage_table_html") or {}),
        )
        .call()
    )

    vehicle_usage_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("vehicle_usage_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Uso del Vehículo",
            data=vehicle_usage_table_html,
            **(params.get("vehicle_usage_sv") or {}),
        )
        .call()
    )

    refuel_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("refuel_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=km_por_viaje,
            raise_if_not_found=False,
            retain_columns=[
                "time",
                "forma_recarga",
                "tipo_combustible",
                "litros_cargados",
                "responsable_recarga",
            ],
            rename_columns={
                "time": "Fecha",
                "forma_recarga": "Estación de servicio",
                "tipo_combustible": "Tipo de combustible",
                "litros_cargados": "Litros cargados",
                "responsable_recarga": "Responsable de la carga",
            },
            drop_columns=None,
            **(params.get("refuel_columns") or {}),
        )
        .call()
    )

    refuel_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("refuel_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dataframe=refuel_columns, **(params.get("refuel_table") or {}))
        .call()
    )

    refuel_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("refuel_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=refuel_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="refuel_table",
            **(params.get("refuel_table_html") or {}),
        )
        .call()
    )

    refuel_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("refuel_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Recargas de combustible",
            data=refuel_table_html,
            **(params.get("refuel_sv") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_apn_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_journeys_sv,
                total_km_sv,
                total_fuel_sv,
                avg_occupants_sv,
                km_over_time_chart_sv,
                driver_ranking_sv,
                vehicle_usage_sv,
                refuel_sv,
            ],
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
